export const TREASURED_COMPATIBLE_MINERALS = new Set([
  "Copper",
  "Seashell",
  "Obsidian",
  "Gold",
  "Platinum",
  "Pearl",
  "Topaz",
  "Malachite",
  "Electrum",
  "Zircon",
  "Silver",
  "Blue Ice",
  "Neodymium",
  "Smoky Quartz",
  "Coral",
  "Titanium",
  "Sapphire",
  "Ruby",
  "Peridot",
  "Silver Clamshell",
  "Onyx",
  "Diopside",
  "Meteoric Iron",
  "Lapis Lazuli",
  "Jade",
  "Ammonite Fossil",
  "Glacial Quartz",
  "Osmium",
  "Opal",
  "Aurorite",
  "Bone",
  "Mercury",
  "Pyronium",
  "Iridium",
  "Emerald",
  "Moonstone",
  "Golden Pearl",
  "Cobalt",
  "Borealite",
  "Rose Gold",
  "Bismuth",
  "Specterite",
  "Dragon Bone",
  "Cinnabar",
  "Fire Opal",
  "Uranium",
  "Palladium",
  "Catseye",
  "Aetherite",
  "Diamond",
  "Tourmaline",
  "Aquamarine",
  "Vortessence",
  "Mythril",
  "Pink Diamond",
  "Inferlume",
  "Flarebloom",
  "Painite",
  "Chrysoberyl",
  "Star Garnet",
  "Bloodstone",
]);
